name: CD Pipeline

on:
  workflow_dispatch:

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: initialize Terraform
        run: |
          cd terraform/
          terraform init -backend-config="bucket=${BUCKET_TF_STATE}" \
                          -backend-config="key=terraform.tfstate" \
                          -backend-config="region=us-east-1"

      - name: plan Terraform
        run: |
          cd terraform/
          terraform plan -out=tfplan

      - name: apply Terraform
        run: |
          cd terraform/
          terraform apply -auto-approve -input=false tfplan

      - name: Get ELB URL from Terraform output
        id: get_elb_url
        run: |
          cd terraform/
          echo "ELB_URL=$(terraform output -raw elb_url)" > $GITHUB_ENV

      - name: Send notification on Slack using Webhooks
        uses: act10ns/slack@v2
        with:
          channel: "#deployments"
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: "Deployment completed successfully. ELB URL: ${{ env.ELB_URL }}"
        if: always()
