name: CD Pipeline

on:
  workflow_dispatch:

env:
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: initialize Terraform
        run: |
          cd terraform/
          terraform init -backend-config="bucket=${BUCKET_TF_STATE}" \
                          -backend-config="key=terraform.tfstate" \
                          -backend-config="region=us-east-1"

      - name: plan Terraform
        run: |
          cd terraform/
          terraform plan -out=tfplan

      - name: apply Terraform
        run: |
          cd terraform/
          terraform apply -auto-approve -input=false tfplan

      - name: Get ELB URL from Terraform output
        id: get_elb_url
        run: |
          cd terraform/
          ELB_URL=$(terraform output -json elb_url | tr -d '"')
          echo "ELB_URL=${ELB_URL}" >> $GITHUB_ENV
          echo "Set environment variable: ELB_URL=${ELB_URL}"

      - name: Notify via Slack
        uses: 8398a7/action-slack@v3
        with:
          channel: "#deployments"
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Deployment completed successfully! ELB URL: ${{ env.ELB_URL }}"
