name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v2

      - name: log into docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        run: |
          docker build -t guytamari/nginx-custom terraform/docker/.
          docker push guytamari/nginx-custom

      - name: Trigger CD pipeline
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -d '{"ref":"main"}' https://api.github.com/repos/${{ github.repository }}/actions/workflows/cd.yaml/dispatches
