name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: check out the repository
        uses: actions/checkout@v2

      - name: log into docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        run: |
          echo ($pwd)
          ls ../terraform/docker/
          docker build -t guytamari/nginx-custom ../terraform/docker/.
          docker push guytamari/nginx-custom

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: initialize Terraform
        run: |
          cd ../terraform
          terraform init

      - name: apply Terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
